config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: :sessions }

  authenticated(:user) { root 'dashboard#index', as: :authenticated_root }
  get :dashboard, to: 'dashboard#index'
  devise_scope(:user) { root to: 'sessions#new' }

  scope controller: :logout do
    get :sign_out, to: 'logout#sign_out_page'
    post :assign_logout_notice_back_url
    get :logout_notice
    get :timedout_user
  end

  resources :passwords, only: %i[index create] do
    collection do
      get :reset
      post :reset, to: 'passwords#validate'
      get :email_sent
      get :invalid
      get :success
      get :edit
      patch :update
    end
  end

  scope module: :organisations, path: '/' do
    get :create_account, to: 'organisations#create_account'
    post :create_account, to: 'organisations#submit_create_account'
    resources :organisations, only: %i[] do
      collection do
        get :how_many_vehicles
        post :how_many_vehicles, to: 'organisations#submit_how_many_vehicles'
        get :cannot_create
        get :sign_in_details
        post :sign_in_details, to: 'organisations#submit_sign_in_details'
        get :email_sent
        get :resend_email
        get :email_verified
        get :email_verification
        get :verification_failed
        get :verification_expired
      end
    end
  end

  scope module: :vehicles_management, path: '/' do
    resources :fleets, only: %i[index], path: 'manage_vehicles' do
      collection do
        post :index, to: 'fleets#submit_search'
        get :add_another_zone, to: 'fleets#add_another_zone'
        get :remove_selected_zone, to: 'fleets#remove_selected_zone'
        post :select_zone, to: 'fleets#select_zone'
        get :vrn_not_found, to: 'fleets#vrn_not_found'
        get :choose_method
        post :choose_method, to: 'fleets#submit_choose_method'
        get :first_upload
        scope controller: :remove_vehicles do
          get :remove_vehicles
          post :remove_vehicles, to: 'remove_vehicles#submit_remove_vehicles'
          get :confirm_remove_vehicle
          delete :confirm_remove_vehicle, to: 'remove_vehicles#delete_vehicle'
          get :confirm_remove_vehicles
          delete :confirm_remove_vehicles, to: 'remove_vehicles#delete_vehicles'
          get :vehicles_to_remove_details
          get :vehicle_not_found
          post :vehicle_not_found, to: 'remove_vehicles#submit_search'
          get :clear_search
        end
        get :assign_remove
        get :remove
        post :remove, to: 'fleets#confirm_remove'
        get :export
        get :edit
        post :submit_edit
      end
    end

    resources :vehicles, only: [] do
      collection do
        get :enter_details
        post :enter_details, to: 'vehicles#submit_details'
        get :details
        post :confirm_details
        get :exempt
        get :incorrect_details
        post :incorrect_details, to: 'vehicles#confirm_incorrect_details'
        get :not_found
        post :not_found, to: 'vehicles#confirm_not_found'
        get :local_exemptions
        post :add_to_fleet
        post :confirm_and_add_exempt_vehicle_to_fleet
      end
    end

    resources :uploads, only: %i[index create] do
      collection do
        get :processing
        get :calculating_chargeability
        get :download_template
      end
    end
  end

  scope module: :payments, path: '/' do
    resources :payments, only: :index do
      collection do
        post :local_authority
        scope '/which_days' do
          get :matrix
          post :matrix, to: 'payments#submit'
          get :vrn_not_found
          post :vrn_not_found, to: 'payments#submit_search'
        end
        get :no_chargeable_vehicles
        get :undetermined_vehicles
        get :clear_search
        get :review
        post :confirm_review
        get :review_details
        get :select_payment_method
        post :select_payment_method, to: 'payments#confirm_payment_method'
        get :initiate, to: 'credit_cards#initiate'
        get :result, to: 'credit_cards#result'
        get :in_progress
        get :success
        get :unsuccessful
        get :post_payment_details
        get :cancel, to: '/direct_debits/debits#cancel'
      end
    end
  end

  scope module: :direct_debits, path: '/' do
    resources :debits, only: %i[index], path: 'direct_debits' do
      collection do
        get :set_up
        post :set_up, to: 'debits#submit_set_up'
        get :first_mandate
        get :confirm
        post :initiate
        get :success
        get :complete_setup
        get :unsuccessful
      end
    end
  end

  scope module: :users_management, path: '/' do
    resources :users, controller: :create_users, only: %i[new create] do
      collection do
        get :index, to: 'users#index'
        get :add_permissions
        post :add_permissions, to: 'create_users#confirm_permissions'
        get :confirmation
        get :set_up
        post :set_up, to: 'create_users#confirm_set_up'
        get :set_up_confirmation
      end
      member do
        get :edit, to: 'edit_users#edit'
        patch :update, to: 'edit_users#update'
        get :remove, to: 'remove_users#remove'
        post :remove, to: 'remove_users#confirm_remove'
      end
    end
  end

  scope module: :account_details, path: '/' do
    get :edit_password, to: 'passwords#edit'
    patch :edit_password, to: 'passwords#update'
    get :primary_users_account_details, to: 'primary_users#primary_account_details'
    resources :primary_users, only: %i[] do
      collection do
        scope controller: :organisation_names do
          get :edit_name
          get :update_name
        end
        scope controller: :emails do
          get :edit_email
          post :update_email
          get :email_sent
          get :resend_email
          get :confirm_email
          get :validate_confirm_email
        end
      end
    end

    scope controller: :account_cancellations do
      get :account_closing_notice
      post :account_closing_notice, to: 'account_cancellations#confirm_account_closing_notice'
      get :account_cancellation
      post :account_cancellation, to: 'account_cancellations#submit_account_cancellation'
      get :account_closed
    end

    get :non_primary_users_account_details, to: 'non_primary_users#non_primary_account_details'
    resources :non_primary_users, only: %i[] do
      collection do
        scope controller: :names do
          get :edit_name
          get :update_name
        end
      end
    end
  end

  scope module: :payment_history, path: '/', controller: :payment_history do
    get :payment_history
    get :payment_history_details
    get :initiate_payment_history_download
    get :payment_history_downloading
    get :payment_history_download
    get :payment_history_link_expired
    get :payment_history_link_no_access
    get :payment_history_export, to: 'payment_history#handle_payment_history_download_link'
    get :payment_history_export_download, to: 'payment_history#handle_payment_history_download_attempt'
  end

  scope controller: :static_pages do
    get :accessibility_statement
    get :cookies
    get :support
    get :privacy_notice
    get :terms_and_conditions
    get :relevant_portal_cookies
  end

  scope controller: :application do
    get :build_id
    get :health
  end

  scope controller: :errors do
    get :not_found
    get :service_unavailable
  end

  scope controller: :relevant_portal do
    get :what_would_you_like_to_do
    post :what_would_you_like_to_do, to: 'relevant_portal#submit_what_would_you_like_to_do'
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/503', to: 'errors#service_unavailable', via: :all
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

##
# Controller class for the static pages
#
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :check_password_age
  before_action :disable_cookies, only: :relevant_portal_cookies

  ##
  # Renders the accessibility statement page
  #
  # ==== Path
  #    GET /accessibility_statement
  #
  def accessibility_statement
    # renders static page
  end

  ##
  # Renders the cookies page
  #
  # ==== Path
  #    GET /cookies
  #
  def cookies
    # renders static page
  end

  ##
  # Renders the support page
  #
  # ==== Path
  #    GET /relevant_portal_cookies
  #
  def relevant_portal_cookies
    # renders static page
  end

  ##
  # Renders the support page
  #
  # ==== Path
  #    GET /support
  #
  def support
    @zones = CleanAirZone.visible_cazes
  end

  ##
  # Renders the privacy notice page
  #
  # ==== Path
  #    GET /privacy_notice
  #
  def privacy_notice
    @zones = CleanAirZone.visible_cazes
  end

  ##
  # Renders the terms and conditions page
  #
  # ==== Path
  #    GET /terms_and_conditions
  #
  def terms_and_conditions
    # renders static page
  end

  private

  # Disable session cookies
  def disable_cookies
    request.session_options[:skip] = true
  end
end

app/views/static_pages/accessibility_statement.html.haml
- title_and_header = 'Accessibility statement for Drive in a Clean Air Zone'
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-xl
        = title_and_header
      %p
        This accessibility statement explains how accessible this service is,
        what to do if you have difficulty using it, and how to report accessibility problems with the service.
      %p
        This service is part of the wider GOV.UK website. There is a separate
        = link_to('accessibility statement',
                  'https://www.gov.uk/help/accessibility-statement',
                  id: 'gov-uk-accessibility-link')
        for the main GOV.UK website.

      %p
        This page only contains information about the Drive in a Clean Air Zone service.

      %h2.govuk-heading-m Using this service

      %p
        The Drive in a Clean Air Zone service allows users to check if their vehicle meets emissions standards and, if not, pay the charge liable in each Clean Air Zone (CAZ).
        Payment is made through GOV Pay, which has a separate
        = succeed '.' do
          = link_to('accessibility statement',
                    'https://www.payments.service.gov.uk/accessibility-statement/',
                    id: 'gov-pay-accessibility-link')
      %p
        This service is operated by the Joint Air Quality Unit (JAQU), a team established jointly between the Department for Environment, Food and Rural Affairs (Defra) and the Department for Transport (DfT).
        We want as many people as possible to be able to use this service.

      %p
        This means you should be able to:
        %ul.govuk-list-govuk-list--bullet
          %li
            %p
              change colours, contrast levels and fonts
          %li
            %p
              zoom in up to 300% without the text spilling off the screen
          %li
            %p
              get from the start of the service to the end using just a keyboard
          %li
            %p
              get from the start of the service to the end using speech recognition software
          %li
            %p
              listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver).
      %p We've also made the website text as simple as possible to understand.
      %p
        = link_to('AbilityNet',
                  'https://mcmw.abilitynet.org.uk/',
                  id: 'ability-net-link')
        has advice on making your device easier to use if you have a disability.

      %h2.govuk-heading-m How accessible is this service?
      %p
        This service has been tested by the Digital Accessibility Centre (DAC) and is fully compliant with the Web Content Accessibility Guidelines version 2.1 AA standard.

      %h2.govuk-heading-m Technical information about this website's accessibility
      %p
        JAQU is committed to making its website accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.

      %p
        This website is fully compliant with the
        = succeed '.' do
          = link_to('Web Content Accessibility Guidelines version 2.1 AA standard',
                    'https://www.w3.org/TR/WCAG21/',
                    id: 'wcag21-guidelines-link')
      %h2.govuk-heading-m How we tested this service
      %p
        This service is tested at least monthly by the team that maintains it, and periodically by external bodies. At the time of publishing, it was last tested externally by
        = link_to('Digital Accessibility Centre Limited',
                  'https://www.digitalaccessibilitycentre.org/',
                  id: 'digital-accessibility-centre-link')
        on the dates listed below.

      %table.govuk-table
        %thead.govuk-table__head
          %tr
            %th.govuk-table__header{scope: 'col'} Service
            %th.govuk-table__header{scope: 'col'} Date tested
        %tbody.govuk-table__body
          %tr.govuk-table__row
            %td.govuk-table__cell{scope: 'row'}
              Check a single vehicle
            %td.govuk-table__cell{scope: 'row'}
              26th November 2019
          %tr.govuk-table__row
            %td.govuk-table__cell{scope: 'row'}
              Pay a charge for a single vehicle
            %td.govuk-table__cell{scope: 'row'}
              25th March 2020
          %tr.govuk-table__row
            %td.govuk-table__cell{scope: 'row'}
              Check and Pay for multiple vehicles
            %td.govuk-table__cell{scope: 'row'}
              30th March 2020

      %h2.govuk-heading-m What to do if you have difficulty using this service
      %p
        If you have difficulty using this service, contact us by:
      %p
        Telephone: 0300 029 8888
        %br
        Monday to Friday, 8am to 4:30pm
        %br
        Find out about call charges
        %br
        = link_to('Online contact form',
                  'https://contact.dvla.gov.uk/caz',
                  id: 'contact-form-link')

      %h2.govuk-heading-m Reporting accessibility problems with this website
      %p
        We're always looking to improve the accessibility of this website.
        If you find any problems that are not listed on this page or think we're not meeting accessibility requirements, let us know using our
        = succeed '.' do
          = link_to('feedback form',
                    'https://contact.dvla.gov.uk/caz',
                    id: 'feedback-form-link')

      %h2.govuk-heading-m Enforcement procedure
      %p
        The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the 'accessibility regulations').
        If you're not happy with how we respond to your complaint,
        = succeed '.' do
          = link_to('contact the Equality Advisory and Support Service (EASS)',
                    'https://www.equalityadvisoryservice.com/',
                    id: 'eass-link')

      %p
        This statement was prepared on 8 July 2020.

app/views/static_pages/help.html.haml
- title_and_header = 'Help'
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-xl= title_and_header

      %p Where the Clean Air Zones are and when you need to pay a charge.

      %table.govuk-table
        %caption.govuk-table__caption
        %thead.govuk-table__head
          %tr.govuk-table__row
            %th.govuk-table__header{scope: 'col'} CAZ
            %th.govuk-table__header{scope: 'col'} Map
            %th.govuk-table__header{scope: 'col'} Zone live
            %th.govuk-table__header{scope: 'col'} Set up bank payments
        %tbody.govuk-table__body
          - @zones.each do |zone|
            %tr.govuk-table__row
              %th.govuk-table__header{scope: 'row'}=zone.name
              %td.govuk-table__cell
                = external_link_to('Zone boundary', zone.boundary_url, id: "#{zone.name.downcase}-map")
              %td.govuk-table__cell=zone.charging_starts
              %td.govuk-table__cell
                - if zone.direct_debit_enabled?
                  = link_to 'Available Now', debits_path
                - else
                  = zone.direct_debit_start_date_text

      %h2.govuk-heading-m Exemptions
      %p There are some national and local exemptions from the charge.

      %h3.govuk-heading-s Local
      %p
        Local exemptions are specific to the local authority of each CAZ and are managed by them. You usually
        have to apply for local exemptions.
      %p
        You can find out more about local exemptions for driving in:
      - @zones.each do |zone|
        %ul.govuk-list-govuk-list--bullet
          %li
            %p
              = external_link_to(zone.name, zone.exemption_url, id: "#{zone.name.downcase}-exemption")

      %h3.govuk-heading-s National
      %p Vehicles that do not have to pay the charge as they are automatically entitled to a national exemption:
      %ul.govuk-list-govuk-list--bullet
        %li
          %p vehicle that’s ultra low emission
        %li
          %p disabled passenger tax class vehicle
        %li
          %p disabled tax class vehicle
        %li
          %p military vehicle
        %li
          %p historic vehicle
        %li
          %p
            vehicle retrofitted with technology accredited by the
            = external_link_to('Clean Vehicle Retrofit Accreditation Scheme',
                               'https://energysavingtrust.org.uk/service/clean-vehicle-retrofit-accreditation-scheme',
                               class: 'govuk-link',
                               id: 'cvras')
            (CVRAS)
        %li
          %p certain types of agricultural vehicles

      %h2.govuk-heading-m How we calculate your charge
      %p Factors we take into account:
      %ul
        %li
          %p vehicle type and its emission standards (eg HGV and Euro V)
        %li
          %p fuel type (eg diesel or petrol)
        %li
          %p class of Clean Air Zone (A, B, C, D)
      %p
        The ULEZ in London uses different factors to calculate it's charge. Which is why the charge you see here may be different from
        = succeed '.' do
          = external_link_to('Transport for London',
                             'https://tfl.gov.uk/modes/driving/ultra-low-emission-zone',
                             class: 'govuk-link',
                             id: 'transport-for-london')

      %h2.govuk-heading-m Refunds
      %p
        You may be able to claim a refund, for example if you paid the charge when you did not need to. Contact the local authority for the zone you paid the charge in to claim a refund:
      %p
        = external_link_to('Read more about refunds',
                           'https://www.gov.uk/guidance/driving-in-a-clean-air-zone',
                           class: 'govuk-link',
                           id: 'about-refunds')

      %h2.govuk-heading-m Important information about vehicle data
      %p The data accuracy of this service is always improving.
      %p Some vehicles' charge results have recently changed.
      %p If you think the charge result you have received is incorrect contact us.
      %p
        You can find out more about Clean Air Zones on our
        = succeed '.' do
          = external_link_to('guidance page',
                             'https://www.gov.uk/guidance/driving-in-a-clean-air-zone',
                             class: 'govuk-link',
                             id: 'guidance')

      %h2.govuk-heading-m Contact Clean Air Zone Support
      %p
        You can contact Clean Air Zone Support if you cannot use the online service or have a question about
        the charge information of any of your vehicles.

      .govuk-details
        .govuk-details__text
          %strong Clean Air Zone Support
          %br
            = external_link_to('Online contact form',
                                Rails.configuration.x.contact_form_link,
                                class: 'govuk-link',
                                id: 'contact-form')
          Telephone: 0300 029 8888
          %br Monday to Friday, 8am to 4:30pm
          = external_link_to('Find out about call charges',
                             'https://www.gov.uk/call-charges',
                             class: 'govuk-link',
                             id: 'call-charges')

app/views/static_pages/support.html.haml
- title_and_header = 'Support'
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-xl= title_and_header

      .govuk-accordion#accorrdion-default{'data-module': 'govuk-accordion'}
        .govuk-accordion__section
          .govuk-accordion__section-header
            %h2.govuk-accordion__section-heading
              %span.govuk-accordion__section-button#accordion-default-heading-1
                Useful dates
          .accordion-default-content-1.govuk-accordion__section-content{'aria-labelledby': 'accordion-default-heading-1'}
            %table.govuk-table
              %caption.govuk-table__caption
              %thead.govuk-table__head
                %tr.govuk-table__row
                  %th.govuk-table__header{scope: 'col'} CAZ
                  %th.govuk-table__header{scope: 'col'} Zone live
                  %th.govuk-table__header{scope: 'col'} Set up bank payments
              %tbody.govuk-table__body
                - @zones.each do |zone|
                  %tr.govuk-table__row
                    %th.govuk-table__header{scope: 'row'}=zone.name
                    %td.govuk-table__cell=zone.charging_starts
                    %td.govuk-table__cell
                      - if zone.direct_debit_enabled?
                        = link_to 'Available Now', debits_path
                      - else
                        = zone.direct_debit_start_date_text

        .govuk-accordion__section
          .govuk-accordion__section-header
            %h2.govuk-accordion__section-heading
              %span.govuk-accordion__section-button#accordion-default-heading-2
                Zone boundaries
          .accordion-default-content-2.govuk-accordion__section-content{'aria-labelledby': 'accordion-default-heading-2'}
            %table.govuk-table
              %caption.govuk-table__caption
              %thead.govuk-table__head
                %tr.govuk-table__row
                  %th.govuk-table__header{scope: 'col'} CAZ
                  %th.govuk-table__header{scope: 'col'} Map
              %tbody.govuk-table__body
                - @zones.each do |zone|
                  %tr.govuk-table__row
                    %th.govuk-table__header{scope: 'row'}=zone.name
                    %td.govuk-table__cell
                      = external_link_to('Zone boundary', zone.boundary_url, id: "#{zone.name.downcase}-map")

        .govuk-accordion__section
          .govuk-accordion__section-header
            %h2.govuk-accordion__section-heading
              %span.govuk-accordion__section-button#accordion-default-heading-3
                How we calculate your charge
          .accordion-default-content-3.govuk-accordion__section-content{'aria-labelledby': 'accordion-default-heading-3'}
            .govuk-body
              %p Factors we take into account:
              %ul
                %li
                  %p vehicle type and its emission standards (eg HGV and Euro V)
                %li
                  %p fuel type (eg diesel or petrol)
                %li
                  %p class of Clean Air Zone (A, B, C, D)
              %p
                The ULEZ in London uses different factors to calculate it's charge. Which is why the charge you see here may be different from
                = succeed '.' do
                  = external_link_to('Transport for London',
                                    'https://tfl.gov.uk/modes/driving/ultra-low-emission-zone',
                                    class: 'govuk-link',
                                    id: 'transport-for-london')

        .govuk-accordion__section
          .govuk-accordion__section-header
            %h2.govuk-accordion__section-heading
              %span.govuk-accordion__section-button#accordion-default-heading-4
                Exemptions
          .accordion-default-content-4.govuk-accordion__section-content{'aria-labelledby': 'accordion-default-heading-4'}
            .govuk-body
              %p There are some national and local exemptions from the charge.

              %h3.govuk-heading-s National
              %p Vehicles that do not have to pay the charge as they are automatically entitled to a national exemption:
              %ul.govuk-list-govuk-list--bullet
                %li
                  %p vehicle that’s ultra low emission
                %li
                  %p disabled passenger tax class vehicle
                %li
                  %p military vehicle
                %li
                  %p historic vehicle
                %li
                  %p
                    vehicle retrofitted with technology accredited by the
                    = external_link_to('Clean Vehicle Retrofit Accreditation Scheme',
                                      'https://energysavingtrust.org.uk/service/clean-vehicle-retrofit-accreditation-scheme',
                                      class: 'govuk-link',
                                      id: 'cvras')
                    (CVRAS)

              %h3.govuk-heading-s Local
              %p
                Local exemptions are specific to the local authority of each CAZ and are managed by them. You usually
                have to apply for local exemptions.
              %p
                You can find out more about local exemptions for driving in:
              - @zones.each do |zone|
                %ul.govuk-list-govuk-list--bullet
                  %li
                    %p
                      = external_link_to(zone.name, zone.exemption_url, id: "#{zone.name.downcase}-exemption")

        .govuk-accordion__section
          .govuk-accordion__section-header
            %h2.govuk-accordion__section-heading
              %span.govuk-accordion__section-button#accordion-default-heading-5
                Payment limit
          .accordion-default-content-5.govuk-accordion__section-content{'aria-labelledby': 'accordion-default-heading-5'}
            %p.govuk-body
              The maximum payment that can be made in a single transaction is £5,000.
              Payments that exceed this limit will need to be split into separate transactions.

        .govuk-accordion__section
          .govuk-accordion__section-header
            %h2.govuk-accordion__section-heading
              %span.govuk-accordion__section-button#accordion-default-heading-5
                What happens when a charge isn't paid
          .accordion-default-content-5.govuk-accordion__section-content{'aria-labelledby': 'accordion-default-heading-5'}
            .govuk-body
              %p
                Payment can be made 6 days before, on the day of travel or by 11:59pm on the 6th day
                after driving in the zone otherwise you may receive a penalty charge notice (PCN).
                The daily charge period runs from midnight to midnight.
              %p
                The PCN will be issued to the registered keeper of the vehicle that has been
                driven into the Clean Air Zone. The amount you need to pay for your PCN may vary
                depending on the Local Authority it was issued by.
              %p
                If you do not pay the penalty within the dates shown on your PCN, you may receive
                a Charge Certificate.

        .govuk-accordion__section
          .govuk-accordion__section-header
            %h2.govuk-accordion__section-heading
              %span.govuk-accordion__section-button#accordion-default-heading-6
                Refunds
          .accordion-default-content-6.govuk-accordion__section-content{'aria-labelledby': 'accordion-default-heading-6'}
            .govuk-body
              %p
                You may be able to claim a refund, for example if you paid the charge when you did not need to. Contact the local authority for the zone you paid the charge in to claim a refund:
              %p
                = external_link_to('Read more about refunds',
                                  'https://www.gov.uk/guidance/driving-in-a-clean-air-zone',
                                  class: 'govuk-link',
                                  id: 'about-refunds')

        .govuk-accordion__section
          .govuk-accordion__section-header
            %h2.govuk-accordion__section-heading
              %span.govuk-accordion__section-button#accordion-default-heading-7
                Important information about vehicle data
          .accordion-default-content-7.govuk-accordion__section-content{'aria-labelledby': 'accordion-default-heading-7'}
            .govuk-body
              %p The data accuracy of this service is always improving. Some vehicles charge results have recently changed.
              %p If you think the charge result you have received is incorrect contact us.
              %p
                You can find out more about Clean Air Zones on our
                = succeed '.' do
                  = external_link_to('guidance page',
                                    'https://www.gov.uk/guidance/driving-in-a-clean-air-zone',
                                    class: 'govuk-link',
                                    id: 'guidance')

        .govuk-accordion__section
          .govuk-accordion__section-header
            %h2.govuk-accordion__section-heading
              %span.govuk-accordion__section-button#accordion-default-heading-8
                Contact Clean Air Zone Support
          .accordion-default-content-8.govuk-accordion__section-content{'aria-labelledby': 'accordion-default-heading-8'}
            .govuk-body
              %p
                You can contact Clean Air Zone Support if you cannot use the online service or have a question about
                the charge information of any of your vehicles.

              .govuk-details
                .govuk-details__text
                  %strong Clean Air Zone Support
                  %br
                    = external_link_to('Online contact form',
                                        Rails.configuration.x.contact_form_link,
                                        class: 'govuk-link',
                                        id: 'contact-form')
                  Telephone: 0300 029 8888
                  %br Monday to Friday, 8am to 4:30pm
                  = external_link_to('Find out about call charges',
                                    'https://www.gov.uk/call-charges',
                                    class: 'govuk-link',
                                    id: 'call-charges')