config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: :sessions }

  authenticated(:user) { root 'dashboard#index', as: :authenticated_root }
  get :dashboard, to: 'dashboard#index'
  devise_scope(:user) { root to: 'sessions#new' }

  scope controller: :logout do
    get :sign_out, to: 'logout#sign_out_page'
    post :assign_logout_notice_back_url
    get :logout_notice
    get :timedout_user
  end

  resources :passwords, only: %i[index create] do
    collection do
      get :reset
      post :reset, to: 'passwords#validate'
      get :email_sent
      get :invalid
      get :success
      get :edit
      patch :update
    end
  end

  scope module: :organisations, path: '/' do
    get :create_account, to: 'organisations#create_account'
    post :create_account, to: 'organisations#submit_create_account'
    resources :organisations, only: %i[] do
      collection do
        get :how_many_vehicles
        post :how_many_vehicles, to: 'organisations#submit_how_many_vehicles'
        get :cannot_create
        get :sign_in_details
        post :sign_in_details, to: 'organisations#submit_sign_in_details'
        get :email_sent
        get :resend_email
        get :email_verified
        get :email_verification
        get :verification_failed
        get :verification_expired
      end
    end
  end

  scope module: :vehicles_management, path: '/' do
    resources :fleets, only: %i[index], path: 'manage_vehicles' do
      collection do
        post :index, to: 'fleets#submit_search'
        get :add_another_zone, to: 'fleets#add_another_zone'
        get :remove_selected_zone, to: 'fleets#remove_selected_zone'
        post :select_zone, to: 'fleets#select_zone'
        get :vrn_not_found, to: 'fleets#vrn_not_found'
        get :choose_method
        post :choose_method, to: 'fleets#submit_choose_method'
        get :first_upload
        scope controller: :remove_vehicles do
          get :remove_vehicles
          post :remove_vehicles, to: 'remove_vehicles#submit_remove_vehicles'
          get :confirm_remove_vehicle
          delete :confirm_remove_vehicle, to: 'remove_vehicles#delete_vehicle'
          get :confirm_remove_vehicles
          delete :confirm_remove_vehicles, to: 'remove_vehicles#delete_vehicles'
          get :vehicles_to_remove_details
          get :vehicle_not_found
          post :vehicle_not_found, to: 'remove_vehicles#submit_search'
          get :clear_search
        end
        get :assign_remove
        get :remove
        post :remove, to: 'fleets#confirm_remove'
        get :export
        get :edit
        post :submit_edit
      end
    end

    resources :vehicles, only: [] do
      collection do
        get :enter_details
        post :enter_details, to: 'vehicles#submit_details'
        get :details
        post :confirm_details
        get :exempt
        get :incorrect_details
        post :incorrect_details, to: 'vehicles#confirm_incorrect_details'
        get :not_found
        post :not_found, to: 'vehicles#confirm_not_found'
        get :local_exemptions
        post :add_to_fleet
        post :confirm_and_add_exempt_vehicle_to_fleet
      end
    end

    resources :uploads, only: %i[index create] do
      collection do
        get :processing
        get :calculating_chargeability
        get :download_template
      end
    end
  end

  scope module: :payments, path: '/' do
    resources :payments, only: :index do
      collection do
        post :local_authority
        scope '/which_days' do
          get :matrix
          post :matrix, to: 'payments#submit'
          get :vrn_not_found
          post :vrn_not_found, to: 'payments#submit_search'
        end
        get :no_chargeable_vehicles
        get :undetermined_vehicles
        get :clear_search
        get :review
        post :confirm_review
        get :review_details
        get :select_payment_method
        post :select_payment_method, to: 'payments#confirm_payment_method'
        get :initiate, to: 'credit_cards#initiate'
        get :result, to: 'credit_cards#result'
        get :in_progress
        get :success
        get :unsuccessful
        get :post_payment_details
        get :cancel, to: '/direct_debits/debits#cancel'
      end
    end
  end

  scope module: :direct_debits, path: '/' do
    resources :debits, only: %i[index], path: 'direct_debits' do
      collection do
        get :set_up
        post :set_up, to: 'debits#submit_set_up'
        get :first_mandate
        get :confirm
        post :initiate
        get :success
        get :complete_setup
        get :unsuccessful
      end
    end
  end

  scope module: :users_management, path: '/' do
    resources :users, controller: :create_users, only: %i[new create] do
      collection do
        get :index, to: 'users#index'
        get :add_permissions
        post :add_permissions, to: 'create_users#confirm_permissions'
        get :confirmation
        get :set_up
        post :set_up, to: 'create_users#confirm_set_up'
        get :set_up_confirmation
      end
      member do
        get :edit, to: 'edit_users#edit'
        patch :update, to: 'edit_users#update'
        get :remove, to: 'remove_users#remove'
        post :remove, to: 'remove_users#confirm_remove'
      end
    end
  end

  scope module: :account_details, path: '/' do
    get :edit_password, to: 'passwords#edit'
    patch :edit_password, to: 'passwords#update'
    get :primary_users_account_details, to: 'primary_users#primary_account_details'
    resources :primary_users, only: %i[] do
      collection do
        scope controller: :organisation_names do
          get :edit_name
          get :update_name
        end
        scope controller: :emails do
          get :edit_email
          post :update_email
          get :email_sent
          get :resend_email
          get :confirm_email
          get :validate_confirm_email
        end
      end
    end

    scope controller: :account_cancellations do
      get :account_closing_notice
      post :account_closing_notice, to: 'account_cancellations#confirm_account_closing_notice'
      get :account_cancellation
      post :account_cancellation, to: 'account_cancellations#submit_account_cancellation'
      get :account_closed
    end

    get :non_primary_users_account_details, to: 'non_primary_users#non_primary_account_details'
    resources :non_primary_users, only: %i[] do
      collection do
        scope controller: :names do
          get :edit_name
          get :update_name
        end
      end
    end
  end

  scope module: :payment_history, path: '/', controller: :payment_history do
    get :payment_history
    get :payment_history_details
    get :initiate_payment_history_download
    get :payment_history_downloading
    get :payment_history_download
    get :payment_history_link_expired
    get :payment_history_link_no_access
    get :payment_history_export, to: 'payment_history#handle_payment_history_download_link'
    get :payment_history_export_download, to: 'payment_history#handle_payment_history_download_attempt'
  end

  scope controller: :static_pages do
    get :accessibility_statement
    get :cookies
    get :support
    get :privacy_notice
    get :terms_and_conditions
    get :relevant_portal_cookies
  end

  scope controller: :application do
    get :build_id
    get :health
  end

  scope controller: :errors do
    get :not_found
    get :service_unavailable
  end

  scope controller: :relevant_portal do
    get :what_would_you_like_to_do
    post :what_would_you_like_to_do, to: 'relevant_portal#submit_what_would_you_like_to_do'
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/503', to: 'errors#service_unavailable', via: :all
end

app/controllers/create_organisations/organisations_controller.rb
# frozen_string_literal: true

##
# Module used for creating an organisation
module CreateOrganisations
  ##
  # Controller used to create a company account
  #
  # rubocop:disable Metrics/ClassLength
  class OrganisationsController < ApplicationController
    skip_before_action :authenticate_user!
    # checks if new_company account_id is present in session
    before_action :check_account_id, only: %i[new_credentials create email_sent]
    # checks if new account details is present in session
    before_action :check_account_details, only: %i[email_sent resend_email]
    # add data to session to render it in the text fields after using `Back` link
    before_action :add_credentials_to_session, only: %i[create]

    ##
    # Renders the create account name page.
    #
    # ==== Path
    #
    #    :GET /organisations
    #
    def new
      @error = alert
    end

    ##
    # Validates submitted account name.
    # If successful, redirects to {:new_credentials}
    # [rdoc-ref:OrganisationsController.new_credentials]
    # If no, redirects to {:new}[rdoc-ref:OrganisationsController.new]
    #
    # ==== Path
    #
    #    POST /organisations
    #
    # ==== Params
    # * +company_name+ - string, account name e.g. 'Company name'
    #
    def set_name
      create_new_account if account_not_created_or_name_changed?
      redirect_to fleet_check_organisations_path
    rescue InvalidCompanyNameException, UnableToCreateAccountException => e
      @error = e.message
      render 'create_organisations/organisations/new'
    end

    ##
    # Renders page to check if fleet have more than 2 vehicles.
    #
    # ==== Path
    #
    #    GET /organisations/fleet_check
    #
    def fleet_check
      # renders static page
    end

    ##
    # Creates Account based on provided details.
    # Validates if account will have more than two vehicles in the fleet.
    #
    # ==== Path
    #
    #    POST /organisations/fleet_check
    #
    def submit_fleet_check
      SessionManipulation::SetFleetCheck.call(session: session, params: company_params)
      CreateOrganisations::ValidateFleetCheck.call(confirm_fleet_check: company_params[:confirm_fleet_check])
      redirect_to new_credentials_organisations_path
    rescue InvalidFleetCheckException => e
      @error = e.message
      render 'create_organisations/organisations/fleet_check'
    rescue AccountForMultipleVehiclesException
      redirect_to cannot_create_organisations_path
    end

    ##
    # Renders page to inform that user cannot create account fot less than two vehicles.
    #
    # ==== Path
    #
    #    GET /organisations/cannot_create
    #
    def cannot_create
      # renders static page
    end

    ##
    # Renders the new email and password page.
    #
    # ==== Path
    #
    #    GET /organisations/new_credentials
    #
    # ==== Params
    # * +company_name+ - string, account name stored in the session e.g. 'Company name'
    #
    def new_credentials
      # renders static page
    end

    ##
    # Validates submitted email and password.
    # If successful, redirects to {email-sent}[rdoc-ref:OrganisationsController.email_sent]
    # If no, redirects to {new_email_and_password}
    # [rdoc-ref:OrganisationsController.new_email_and_password]
    #
    # ==== Path
    #
    #    POST /organisations/new_credentials
    #
    # ==== Params
    # * +company_name+ - string, account name stored in the session e.g. 'Company name'
    #
    def create
      user = CreateOrganisations::CreateUserAccount.call(
        organisations_params: organisations_params,
        account_id: new_account['account_id'],
        verification_url: email_verification_organisations_url
      )
      new_account.merge!(user.serializable_hash.stringify_keys)
      redirect_to email_sent_organisations_path
    rescue NewPasswordException => e
      @errors = e.errors_object
      render :new_credentials
    end

    ##
    # Renders the email sent page.
    #
    # ==== Path
    #
    #    :GET /fleets/organisation-account/email-sent
    #
    def email_sent
      @email = User.new(new_account).email
    end

    def resend_email
      AccountsApi.resend_verification(
        account_id: new_account['account_id'],
        user_id: new_account['user_id'],
        verification_url: email_verification_organisations_url
      )
      redirect_to email_sent_organisations_path
    end

    ##
    # Checks the verification token.
    # If the token is valid it calls backend to mark the email address as verified
    # and redirects to :email_verified
    # If verification fails it redirects to :verification_failed
    #
    # ==== Path
    #
    #    :GET /fleets/organisation-account/email-verification
    #
    # ==== Params
    # * +token+ - string, encrypted token with verification data
    #
    def email_verification
      verification_status = CreateOrganisations::VerifyAccount.call(token: params[:token])
      path = verification_paths[verification_status]
      session['new_account'] = nil
      redirect_to path
    end

    ##
    # Renders the email verified page.
    #
    # ==== Path
    #
    #    :GET /fleets/organisation-account/email-verified
    #
    def email_verified
      @user = User.new
    end

    ##
    # Renders the error page if verification fails.
    #
    # ==== Path
    #
    #    :GET /organisations/verification_failed
    #
    def verification_failed
      # renders static page
    end

    ##
    # Renders the verification expired page.
    #
    # ==== Path
    #
    #    :GET /organisations/verification_expired
    #
    def verification_expired
      # renders static page
    end

    private

    # Defines redirect for verification status
    def verification_paths
      {
        invalid: verification_failed_organisations_path,
        expired: verification_expired_organisations_path,
        success: email_verified_organisations_path
      }
    end

    # Check if account already created or name changed.
    def account_not_created_or_name_changed?
      new_account['account_id'].blank? || new_account['company_name'] != company_params['company_name']
    end

    # Creates Account and store details in session
    def create_new_account
      SessionManipulation::SetCompanyName.call(session: session, params: company_params)
      account_id = CreateOrganisations::CreateAccount.call(company_name: new_account['company_name'])
      SessionManipulation::SetAccountId.call(session: session,
                                             params: { 'account_id' => account_id })
    end

    # Returns the list of permitted params
    def organisations_params
      params.require(:organisations).permit(:email, :email_confirmation, :password,
                                            :password_confirmation)
    end

    # Returns the list of permitted params
    def company_params
      return {} if params[:organisations].blank?

      params.require(:organisations).permit(:company_name, :confirm_fleet_check)
    end

    # Checks if account_id is present in the session.
    # If not, redirects to root path.
    def check_account_id
      return if new_account['account_id']

      Rails.logger.warn('Account id is missing in the session. Redirecting to :root_path')
      redirect_to root_path
    end

    # Checks if new account details is present in the session.
    # If not, redirects to root path.
    def check_account_details
      Rails.logger.warn('Checking credentials from the session')
      redirect_to root_path if (
        %w[email owner user_id account_id account_name permissions login_ip] - new_account.keys
      ).present?
    end

    # Add a new company credentials to the session
    def add_credentials_to_session
      Rails.logger.warn('Adding credentials to the session')
      new_account.merge!(
        'email' => organisations_params['email'],
        'email_confirmation' => organisations_params['email_confirmation']
      )
    end

    # Returns new account details from session
    def new_account
      (session['new_account'] || {}).stringify_keys!
    end
  end
  # rubocop:enable Metrics/ClassLength
end

app/views/organisations/organisations/cannot_create.html.haml
- title_and_header = 'Business accounts are for multiple vehicles'
- content_for(:title, title_and_header)

= link_to 'Back', how_many_vehicles_organisations_path, class: 'govuk-back-link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-l= title_and_header
      %p
        - if @payment_features_enabled
          = succeed '.' do
            If you are only paying for 1 vehicle, the easiest and quickest option is to go to
            = link_to 'Pay a charge for a single vehicle', Rails.configuration.x.payments_ui_url
        - else
          = succeed '.' do
            If you are only checking 1 vehicle, the easiest and quickest option is to
            = link_to 'Check a charge for a single vehicle', Rails.configuration.x.check_air_standard_url

app/views/organisations/organisations/create_account.html.haml
- title_and_header = 'Create a business account'
- content_for(:title, title_and_header)

= link_to 'Back', root_path, class: 'govuk-back-link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      = render 'shared/error_summary', error_msg_div: '#company_name-error', error_msg: "#{@error}" if @error

      %h1.govuk-heading-l= title_and_header
      %p
      %span#create-account-hint.govuk-hint
        Upload and pay the charge for multiple vehicles.

      %p
        = succeed '.' do
          By creating an account, you agree to Drive in a Clean Air Zone's
          = link_to 'Terms and conditions', terms_and_conditions_path, class: 'govuk-link'

      %fieldset.govuk-fieldset{'aria-describedby': 'create-account-hint'}
        %legend.govuk-visually-hidden Create account fields

        = form_for('organisations',
                   url: create_account_path,
                   method: :post,
                   html: {autocomplete: :on, novalidate: 'novalidate', spellcheck: false}) do |f|

          .govuk-form-group{class: ('govuk-form-group--error' if @error)}
            = f.label :company_name, I18n.t('company_name_form.company_name_missing'), class: 'govuk-label'

            - if @error
              %span#company_name-error.govuk-error-message
                %span.govuk-visually-hidden Error:
                = (@error.include?('exists')) ? @error.remove('reset your password') : @error
                = link_to 'reset your password', reset_passwords_path if @error.include? 'exists'

            = f.text_field :company_name,
                            class: determinate_input_class(@error),
                            value: session.dig('new_account', 'company_name')

          = submit_tag 'Continue', class: 'govuk-button', 'data-module': 'govuk-button'

        %p
          If you already have an account you can
          = link_to('sign in', new_user_session_path, id: 'sign-in-button')

app/views/organisations/organisations/email_sent.html.haml
- title_and_header = 'Verification email'
- content_for(:title, title_and_header)

= link_to 'Back', sign_in_details_organisations_path, class: 'govuk-back-link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-l
        = title_and_header
      %p
        We've sent a verification email to
        = succeed '.' do
          = @email
        This can take a few minutes to arrive.

      %p If you do not get an email:
      %ul.govuk-list.govuk-list--bullet
        %li check your spam or junk folders
        %li check you have entered the correct email
        %li
          = link_to("resend the email", resend_email_organisations_path)

app/views/organisations/organisations/email_verified.haml
- title_and_header = 'Your business account has been created'
- content_for(:title, title_and_header)
- errors = request.env['warden'].errors

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-xl
        = title_and_header
      %p
        Your email address has been verified and your business account has been activated.
      %p
        Enter your email address and password to sign in.

      = form_for(@user, as: @user, url: session_path(@user)) do |f|
        = render 'shared/sign_in/error_summary', errors: errors if errors.any?
        %fieldset.govuk-fieldset
          %legend.govuk-visually-hidden
            Submit your login credentials
          = render 'shared/sign_in/email_field', form: f, errors: errors
          = render 'shared/sign_in/password_field', form: f, errors: errors
        %p
          = link_to('Forgotten your password?', reset_passwords_path)
        = f.submit 'Continue', class: 'govuk-button', 'data-module': 'govuk-button'

app/views/organisations/organisations/how_many_vehicles.html.haml
- title_and_header = 'How many vehicles do you want to add to the business account?'
- content_for(:title, title_and_header)

= link_to 'Back', create_account_path, class: 'govuk-back-link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-l
        = title_and_header
      %p

      %fieldset.govuk-fieldset{'aria-describedby': 'create-account-hint'}
        %legend.govuk-visually-hidden Create account fields

        = form_for('organisations', url: how_many_vehicles_organisations_path, method: :post,
            html: { autocomplete: :on, novalidate: 'novalidate', spellcheck: false }) do |f|
          .govuk-form-group{class: ('govuk-form-group--error' if @error)}
            %fieldset.govuk-fieldset
              - if @error
                %span#confirm-delete-error.govuk-error-message
                  %span.govuk-visually-hidden Error:
                  = @error

              .govuk-radios
                .govuk-radios__item
                  %input#confirm-fleet-check-1.govuk-radios__input{name: 'organisations[confirm_fleet_check]', type: 'radio', value: 'less_than_two', checked: checked_fleet_checked?('less_than_two') }
                  %label.govuk-label.govuk-radios__label{for: 'confirm-fleet-check-1'}
                    Less than two
                .govuk-radios__item
                  %input#confirm-fleet-check-2.govuk-radios__input{name: 'organisations[confirm_fleet_check]', type: 'radio', value: 'two_or_more', checked: checked_fleet_checked?('two_or_more')}
                  %label.govuk-label.govuk-radios__label{for: 'confirm-fleet-check-2'}
                    Two or more

          = f.submit 'Continue', class: 'govuk-button', 'data-module': 'govuk-button'

app/views/organisations/organisations/sign_in_details.html.haml
- title_and_header = 'Sign in details'
- content_for(:title, title_and_header)

= link_to 'Back', how_many_vehicles_organisations_path, class: 'govuk-back-link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds

      - if @errors.present?
        .govuk-error-summary{'aria-labelledby': 'error-summary-title',
                             'data-module': 'govuk-error-summary',
                             role: 'alert',
                             tabindex: '-1'}
          %h2#error-summary-title.govuk-error-summary__title
            There is a problem
          .govuk-error-summary__body
            %ul.govuk-list.govuk-error-summary__list
              %li
                - remove_duplicated_messages(@errors).each_with_index do |error, index|
                  %li.custom-csv-error
                    = link_to(error.first, "##{error.second}-error", id: "#{error.second}-#{index}")

      = form_for('organisations', url: sign_in_details_organisations_path, method: :post,
        html: { autocomplete: :on, novalidate: true, spellcheck: false }) do |f|

        %fieldset.govuk-fieldset
          %legend.govuk-fieldset__legend.govuk-fieldset__legend--xl
            %h1.govuk-fieldset__heading
              = title_and_header

        - if @errors.present?
          = render 'organisations/organisations/form_input/errored', form: f, errors: @errors
        - else
          = render 'organisations/organisations/form_input/normal', form: f

        %br
        = f.submit 'Continue', class: 'govuk-button', 'data-module': 'govuk-button'

app/views/organisations/organisations/verification_expired.html.haml
- title_and_header = 'Your account could not be verified'
- content_for(:title, title_and_header)

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-xl
        = title_and_header
      %p
        The link in your verification email has expired.
        %br
        Go to
        = link_to 'Create an account', create_account_path
        to start the process again.

app/views/organisations/organisations/verification_failed.html.haml
- title_and_header = 'Account verification failed'
- content_for(:title, title_and_header)

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h1.govuk-heading-xl= title_and_header
      %p The link you used doesn't work.
      %p
        If you already have an account you can
        = link_to('sign in', new_user_session_path, class: 'govuk-link')
      %p
        If you don't have an account you can
        = link_to('create an account', create_account_path, class: 'govuk-link')

      %p= link_to('Forgotten your password?', reset_passwords_path)