config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: :sessions }

  authenticated(:user) { root 'dashboard#index', as: :authenticated_root }
  get :dashboard, to: 'dashboard#index'
  devise_scope(:user) { root to: 'sessions#new' }

  scope controller: :logout do
    get :sign_out, to: 'logout#sign_out_page'
    post :assign_logout_notice_back_url
    get :logout_notice
    get :timedout_user
  end

  resources :passwords, only: %i[index create] do
    collection do
      get :reset
      post :reset, to: 'passwords#validate'
      get :email_sent
      get :invalid
      get :success
      get :edit
      patch :update
    end
  end

  scope module: :organisations, path: '/' do
    get :create_account, to: 'organisations#create_account'
    post :create_account, to: 'organisations#submit_create_account'
    resources :organisations, only: %i[] do
      collection do
        get :how_many_vehicles
        post :how_many_vehicles, to: 'organisations#submit_how_many_vehicles'
        get :cannot_create
        get :sign_in_details
        post :sign_in_details, to: 'organisations#submit_sign_in_details'
        get :email_sent
        get :resend_email
        get :email_verified
        get :email_verification
        get :verification_failed
        get :verification_expired
      end
    end
  end

  scope module: :vehicles_management, path: '/' do
    resources :fleets, only: %i[index], path: 'manage_vehicles' do
      collection do
        post :index, to: 'fleets#submit_search'
        get :add_another_zone, to: 'fleets#add_another_zone'
        get :remove_selected_zone, to: 'fleets#remove_selected_zone'
        post :select_zone, to: 'fleets#select_zone'
        get :vrn_not_found, to: 'fleets#vrn_not_found'
        get :choose_method
        post :choose_method, to: 'fleets#submit_choose_method'
        get :first_upload
        scope controller: :remove_vehicles do
          get :remove_vehicles
          post :remove_vehicles, to: 'remove_vehicles#submit_remove_vehicles'
          get :confirm_remove_vehicle
          delete :confirm_remove_vehicle, to: 'remove_vehicles#delete_vehicle'
          get :confirm_remove_vehicles
          delete :confirm_remove_vehicles, to: 'remove_vehicles#delete_vehicles'
          get :vehicles_to_remove_details
          get :vehicle_not_found
          post :vehicle_not_found, to: 'remove_vehicles#submit_search'
          get :clear_search
        end
        get :assign_remove
        get :remove
        post :remove, to: 'fleets#confirm_remove'
        get :export
        get :edit
        post :submit_edit
      end
    end

    resources :vehicles, only: [] do
      collection do
        get :enter_details
        post :enter_details, to: 'vehicles#submit_details'
        get :details
        post :confirm_details
        get :exempt
        get :incorrect_details
        post :incorrect_details, to: 'vehicles#confirm_incorrect_details'
        get :not_found
        post :not_found, to: 'vehicles#confirm_not_found'
        get :local_exemptions
        post :add_to_fleet
        post :confirm_and_add_exempt_vehicle_to_fleet
      end
    end

    resources :uploads, only: %i[index create] do
      collection do
        get :processing
        get :calculating_chargeability
        get :download_template
      end
    end
  end

  scope module: :payments, path: '/' do
    resources :payments, only: :index do
      collection do
        post :local_authority
        scope '/which_days' do
          get :matrix
          post :matrix, to: 'payments#submit'
          get :vrn_not_found
          post :vrn_not_found, to: 'payments#submit_search'
        end
        get :no_chargeable_vehicles
        get :undetermined_vehicles
        get :clear_search
        get :review
        post :confirm_review
        get :review_details
        get :select_payment_method
        post :select_payment_method, to: 'payments#confirm_payment_method'
        get :initiate, to: 'credit_cards#initiate'
        get :result, to: 'credit_cards#result'
        get :in_progress
        get :success
        get :unsuccessful
        get :post_payment_details
        get :cancel, to: '/direct_debits/debits#cancel'
      end
    end
  end

  scope module: :direct_debits, path: '/' do
    resources :debits, only: %i[index], path: 'direct_debits' do
      collection do
        get :set_up
        post :set_up, to: 'debits#submit_set_up'
        get :first_mandate
        get :confirm
        post :initiate
        get :success
        get :complete_setup
        get :unsuccessful
      end
    end
  end

  scope module: :users_management, path: '/' do
    resources :users, controller: :create_users, only: %i[new create] do
      collection do
        get :index, to: 'users#index'
        get :add_permissions
        post :add_permissions, to: 'create_users#confirm_permissions'
        get :confirmation
        get :set_up
        post :set_up, to: 'create_users#confirm_set_up'
        get :set_up_confirmation
      end
      member do
        get :edit, to: 'edit_users#edit'
        patch :update, to: 'edit_users#update'
        get :remove, to: 'remove_users#remove'
        post :remove, to: 'remove_users#confirm_remove'
      end
    end
  end

  scope module: :account_details, path: '/' do
    get :edit_password, to: 'passwords#edit'
    patch :edit_password, to: 'passwords#update'
    get :primary_users_account_details, to: 'primary_users#primary_account_details'
    resources :primary_users, only: %i[] do
      collection do
        scope controller: :organisation_names do
          get :edit_name
          get :update_name
        end
        scope controller: :emails do
          get :edit_email
          post :update_email
          get :email_sent
          get :resend_email
          get :confirm_email
          get :validate_confirm_email
        end
      end
    end

    scope controller: :account_cancellations do
      get :account_closing_notice
      post :account_closing_notice, to: 'account_cancellations#confirm_account_closing_notice'
      get :account_cancellation
      post :account_cancellation, to: 'account_cancellations#submit_account_cancellation'
      get :account_closed
    end

    get :non_primary_users_account_details, to: 'non_primary_users#non_primary_account_details'
    resources :non_primary_users, only: %i[] do
      collection do
        scope controller: :names do
          get :edit_name
          get :update_name
        end
      end
    end
  end

  scope module: :payment_history, path: '/', controller: :payment_history do
    get :payment_history
    get :payment_history_details
    get :initiate_payment_history_download
    get :payment_history_downloading
    get :payment_history_download
    get :payment_history_link_expired
    get :payment_history_link_no_access
    get :payment_history_export, to: 'payment_history#handle_payment_history_download_link'
    get :payment_history_export_download, to: 'payment_history#handle_payment_history_download_attempt'
  end

  scope controller: :static_pages do
    get :accessibility_statement
    get :cookies
    get :support
    get :privacy_notice
    get :terms_and_conditions
    get :relevant_portal_cookies
  end

  scope controller: :application do
    get :build_id
    get :health
  end

  scope controller: :errors do
    get :not_found
    get :service_unavailable
  end

  scope controller: :relevant_portal do
    get :what_would_you_like_to_do
    post :what_would_you_like_to_do, to: 'relevant_portal#submit_what_would_you_like_to_do'
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/503', to: 'errors#service_unavailable', via: :all
end

app/controllers/vehicles_management/fleets_controller.rb
# frozen_string_literal: true

##
# Module used for manage vehicles flow
module VehiclesManagement
  ##
  # Controller used to manage fleet
  #
  class FleetsController < ApplicationController # rubocop:disable Metrics/ClassLength
    include CheckPermissions
    include ChargeabilityCalculator
    include PaymentFeatures

    before_action -> { check_permissions(allow_manage_vehicles?) }
    before_action :assign_fleet
    before_action :set_cache_headers, only: :index
    before_action :check_job_status, only: :index
    before_action :clear_user_data, only: :index

    ##
    # Renders manage fleet page. If the fleet is empty, redirects to :choose_method
    #
    # ==== Path
    #
    #    :GET /fleets
    #
    # ==== Params
    #
    # * +page+ - used to paginate vehicles list, defaults to 1, present in the query params
    # * +only_chargeable+ - flag, to filter out non-charged vehicles
    # * +page_size+ - integer value, to manipulate number of vehicles on the page
    # * +vrn+ - alphanumeric character part of vrn number
    #
    def index
      return redirect_to choose_method_fleets_path if @fleet.empty?

      assign_index_variables
    rescue BaseApi::Error400Exception
      return redirect_to fleets_path unless params[:page] == 1
    end

    ##
    # Action adds another zone on the Vehicle Management page if there are more than 3 CAZ
    # available. Redirect back to previous page.
    #
    # ==== Path
    #
    #    :GET /fleets/add_another_zone
    #
    def add_another_zone
      VehiclesManagement::DynamicCazes::AddAnotherCaz.call(session: session)
      reload_dynamic_table
    end

    ##
    # Action removes selected zone on the Vehicle Management page if there are
    # more than 3 CAZ available. Redirect back to previous page.
    #
    # ==== Path
    #
    #    :GET /fleets/remove_selected_zone
    #
    # ==== Params
    #
    # * +key+ - uuid key of CAZ select box
    #
    def remove_selected_zone
      if params[:key].present?
        VehiclesManagement::DynamicCazes::RemoveSelectedCaz.call(
          session: session, user: current_user, key: params[:key]
        )
      end
      reload_dynamic_table
    end

    ##
    # Action changes selected zone on the Vehicle Management page if there are
    # more than 3 CAZ available. Redirect back to previous page.
    #
    # ==== Path
    #
    #    :GET /fleets/select_zone
    #
    # ==== Params
    #
    # * +key+ - uuid key CAZ select box
    # * +zone_id+ - uuid of selected CAZ
    #
    def select_zone
      if params[:key].present? && params[:zone_id].present?
        VehiclesManagement::DynamicCazes::SelectCaz.call(
          session: session, user: current_user, key: params[:key],
          zone_id: params[:zone_id]
        )
      end
      reload_dynamic_table
    end

    ##
    # Validates a search form and redirects to the proper page
    #
    # ==== Path
    #
    #    :POST /manage_vehicles/submit_search
    #
    def submit_search
      form = SearchVrnForm.new(params[:vrn])
      per_page = (params[:per_page] || 10).to_i
      if form.valid? && @fleet.pagination(vrn: form.vrn, per_page: per_page).total_vehicles_count.zero?
        return redirect_to vrn_not_found_fleets_path(vrn: form.vrn, per_page: per_page)
      end

      redirect_to_proper_page(form)
    end

    ##
    # Renders no search results page when no vrn is found
    #
    # ==== Path
    #
    #    :GET /manage_vehicles/vrn_not_found
    #
    def vrn_not_found
      @search = params[:vrn]
    end

    ##
    # Renders submission method selection page
    #
    # ==== Path
    #
    #    :GET /manage_vehicles/choose_method
    #
    def choose_method
      # renders static page
    end

    ##
    # Validates the submission method form and redirects to selected method screen.
    #
    # ==== Path
    #
    #    :POST /manage_vehicles/choose_method
    #
    # ==== Params
    # * +submission-method+ - manual or upload - selected submission method
    #
    def submit_choose_method
      form = VehiclesManagement::SubmissionMethodForm.new(choose_method: params['submission-method'])
      session[:choose_method] = form.choose_method
      if form.valid?
        redirect_to form.manual? ? enter_details_vehicles_path : uploads_path
      else
        @errors = form.errors
        render :choose_method
      end
    end

    ##
    # Renders the view for first CSV upload
    #
    # ==== Path
    #
    #    :GET /manage_vehicles/first_upload
    #
    def first_upload
      # renders static page
    end

    ##
    # Downloads a csv file from AWS S3
    #
    # ==== Path
    #
    #     GET /manage_vehicles/export
    #
    def export
      file_url = AccountsApi::Accounts.csv_exports(
        account_id: current_user.account_id,
        user_beta_tester: current_user.beta_tester
      )
      redirect_to file_url
    end

    ##
    # Renders edit tab
    #
    # ==== Path
    #
    #     GET /manage_vehicles/edit
    #
    def edit
      # renders static page with Manage Fleets tab
    end

    ##
    # Validates an edit fleet form and redirects to the proper page.
    #
    # ==== Path
    #
    #     POST /manage_vehicles/submit_edit
    #
    def submit_edit
      form = UsersManagement::EditFleetForm.new(params[:edit_option])
      if form.valid?
        redirect_to determine_edit_fleet_path(params[:edit_option])
      else
        flash.now.alert = form.first_error_message
        render :edit
      end
    end

    private

    # Creates instant variable with fleet object
    def assign_fleet
      @fleet = current_user.fleet
    end

    # Clears upload job data
    # Clears show_continue_button from session when user lands on fleets page after end of CSV import
    def clear_user_data
      clear_upload_job_data
      session[:show_continue_button] = nil if session[:show_continue_button] == true
    end

    # Assign variables needed in :index view
    def assign_index_variables
      page = (params[:page] || 1).to_i
      per_page = (params[:per_page] || 10).to_i
      @search = params[:vrn]
      form = SearchVrnForm.new(@search)
      if form.valid?
        fetch_pagination_and_zones(page, per_page, @search)
      else
        fetch_pagination_and_zones(page, per_page)
      end
      assign_payment_enabled
    end

    # Load selected zones from session or AccountsApi
    def load_selected_zones
      @selected_zones = VehiclesManagement::DynamicCazes::SelectedCazes.call(
        session: session, user: current_user
      )
    end

    # reloads dynamic table on View Charges page using JS or redirect back to fleets page
    def reload_dynamic_table
      assign_index_variables
      respond_to do |format|
        format.js { render 'reload_dynamic_table' }
        format.html { redirect_back(fallback_location: fleets_path) }
      end
    end

    # Make api calls
    def fetch_pagination_and_zones(page = 1, per_page = 10, vrn = nil)
      @pagination = @fleet.pagination(
        page: page,
        per_page: per_page,
        only_chargeable: params[:only_chargeable],
        vrn: vrn
      )
      @zones = current_user.beta_tester ? CleanAirZone.all : CleanAirZone.visible_cazes
      load_selected_zones if @zones.count > 3
    end

    # Loads error from form if needed and redirect to fleets index with appropriate params
    def redirect_to_proper_page(form)
      redirect_to fleets_path(vrn: form.vrn), alert: form.first_error_message
    end

    # Determine path to edit fleet option.
    def determine_edit_fleet_path(edit_option)
      case edit_option
      when 'add_single'
        enter_details_vehicles_path
      when 'add_multiple'
        uploads_path
      else
        clear_remove_vehicles
        remove_vehicles_fleets_path
      end
    end

    # Clears remove vehicles data from the session.
    def clear_remove_vehicles
      session[:remove_vehicles_list] = nil
      session[:remove_vehicles_vrn_search] = nil
    end
  end
end

app/helpers/remove_vehicles_helper.rb
# frozen_string_literal: true

# View helpers for remove vehicles flow.
module RemoveVehiclesHelper
  # Check of vrn was already checked by user.
  def remove_vrn_checked?(vrn)
    session['remove_vehicles_list']&.include?(vrn)
  end

  # Number of selected vrns.
  def selected_vrns_count
    session['remove_vehicles_list']&.count
  end

  # The list of vehicles to remove in session.
  def remove_vehicles_list
    session['remove_vehicles_list']
  end
end

app/views/vehicles_management/remove_vehicles/_pagination.html.haml
- page = @pagination.page
- total_pages = @pagination.total_pages

%nav.moj-pagination#pagination-label
  %p.govuk-visually-hidden{'aria-labelledby': 'pagination-label'}
    Pagination navigation
  %ul.moj-pagination__list
    - unless page == 1
      = render 'pagination_button', button_text: 'Previous', page: page - 1, form_class: 'prev'

    - fleets_paginated_pages(page, total_pages).each do |i|
      = render 'pagination_button', button_text: i, page: i, active: page == i

    - unless page == total_pages
      = render 'pagination_button', button_text: 'Next', page: page + 1, form_class: 'next'

  - unless page > total_pages
    %p.moj-pagination__results
      Showing
      %b
        = @pagination.range_start
      to
      %b
        = @pagination.range_end
      of
      %b
        = @pagination.total_vehicles_count
      results

app/views/vehicles_management/remove_vehicles/_pagination_button.html.haml
- active ||= false
- form_class ||= nil
- id = "pagination-button-#{transform_to_id(button_text)}"

- if page == '...'
  %li.moj-pagination__item= button_text
- elsif active
  %li.moj-pagination__item.moj-pagination__item--active{id: id}
    = button_text
    - if button_text.is_a?(Integer)
      %span.govuk-visually-hidden
        page
- else
  %li.moj-pagination__item{id: id, class: ("moj-pagination__item--#{form_class}" if form_class)}
    = link_to(remove_vehicles_fleets_path(page: page,
                                          vrn: params[:vrn],
                                          per_page: params[:per_page]),
                                          class: 'moj-pagination__link page-number') do
      = button_text
      - if button_text.is_a?(Integer)
        %span.govuk-visually-hidden
          page
      - if button_text.is_a?(String)
        %span.govuk-visually-hidden
          set of pages

app/views/vehicles_management/remove_vehicles/_per_page.html.haml
= form_tag(remove_vehicles_fleets_path, method: :get, id: 'per-page-form') do
  .govuk-form-group
    %fieldset.govuk-fieldset{'aria-describedby': 'per-page-dropdown'}
      %legend.govuk-visually-hidden Results per page
      = select_tag('per_page',
                   options_for_select(@pagination.results_per_page, params[:per_page]),
                   class: 'govuk-select moj-pagination__results results-per-page-select',
                   id: 'per-page-dropdown')
      = label_tag('per-page-dropdown',
                  'Results per page',
                  class: 'govuk-label moj-pagination__results results-per-page-select')
  = javascript_pack_tag 'perPage'

app/views/vehicles_management/remove_vehicles/_search.html.haml
.govuk-form-group
  %label.govuk-label{for: 'vrn-search'}
    Search for a number plate
  - if alert && alert.include?(I18n.t('vrn_form.errors.vrn_missing'))
    = render 'vehicles_management/remove_vehicles/vrn_input/errored', message: alert
  - else
    = render 'vehicles_management/remove_vehicles/vrn_input/normal'
  %input{value: 'Search',
         type: 'button',
         id: 'search-form-submit',
         class: 'govuk-button govuk-button--secondary',
         'data-module': 'govuk-button'}

- if @vrn.present?
  %p
    = link_to('Clear search (does not remove your selections)',
              clear_search_payments_path,
              id: 'clear-search-link',
              class: 'govuk-link')

app/views/vehicles_management/remove_vehicles/_table.html.haml
%table.govuk-table
  %thead.govuk-table__head
    %tr.govuk-table__row
      %th.govuk-table__header{scope: 'col', colspan: 2}
        Number plate
  %tbody.govuk-table__body
    - @pagination.vrn_list.each do |vrn|
      %tr.govuk-table__row
        %td.govuk-table__cell.vrn
          = vrn

        %td.govuk-table__cell
          .govuk-checkboxes__item
            %input.govuk-checkboxes__input{name: 'remove_vehicles[]',
                                           value: vrn,
                                           id: vrn,
                                           type: 'checkbox',
                                           checked: remove_vrn_checked?(vrn)}
            %label.govuk-label.govuk-checkboxes__label{for: vrn}
              %span.govuk-visually-hidden
                = vrn

app/views/vehicles_management/remove_vehicles/confirm_remove_vehicle.html.haml
- title_and_header = raw("Remove #{remove_vehicles_list.first}?")
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      = render 'shared/error_summary', error_msg_div: '#confirm-delete-error', error_msg: alert if alert

      = form_tag confirm_remove_vehicle_fleets_path, method: :delete do
        .govuk-form-group{class: ('govuk-form-group--error' if alert)}
          %fieldset.govuk-fieldset
            %legend.govuk-fieldset__legend.govuk-fieldset__legend--l
              %h1.govuk-fieldset__heading=title_and_header

            - if alert
              %span#confirm-delete-error.govuk-error-message
                %span.govuk-visually-hidden Error:
                = alert

            .govuk-radios
              .govuk-radios__item
                %input#confirm-delete-1.govuk-radios__input{name: 'confirm-delete', type: 'radio', value: 'yes'}
                %label.govuk-label.govuk-radios__label{for: 'confirm-delete-1'}
                  Yes
              .govuk-radios__item
                %input#confirm-delete-2.govuk-radios__input{name: 'confirm-delete', type: 'radio', value: 'no'}
                %label.govuk-label.govuk-radios__label{for: 'confirm-delete-2'}
                  No
        = submit_tag 'Continue', class: 'govuk-button', 'data-module': 'govuk-button'

app/views/vehicles_management/remove_vehicles/confirm_remove_vehicles.html.haml
- title_and_header = 'Remove vehicles from your list?'
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper.govuk-main-wrapper--auto-spacing#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      - if alert
        = render 'shared/error_summary', error_msg_div: '#confirm-vehicle-details-error', error_msg: alert

      %h2.govuk-heading-l= title_and_header

      %dl.govuk-summary-list
        .govuk-summary-list__row
          %dt.govuk-summary-list__key Vehicles to remove
          %dd.govuk-summary-list__value
            = @vrns_count
          %dd.govuk-summary-list__actions
            = link_to 'View details', vehicles_to_remove_details_fleets_path

      = link_to 'Remove',
                 confirm_remove_vehicles_fleets_path,
                 method: :delete,
                 class: 'govuk-button',
                 id: 'remove'

app/views/vehicles_management/remove_vehicles/remove_vehicles.html.haml
- title_and_header = 'Select vehicles to remove'
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper.govuk-main-wrapper--auto-spacing#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds

      = render 'shared/error' if alert
      %h2.govuk-heading-l= title_and_header
      = render 'vehicles_management/remove_vehicles/search'

      .govuk-form-group
        %fieldset.govuk-fieldset
          %legend.govuk-visually-hidden Select vehicles to remove

          = form_for(remove_vehicles_fleets_path, method: :post, html: { id: 'remove-vehicles-form' }) do
            = hidden_field_tag('vrns_on_page', @pagination.vrn_list)
            = hidden_field_tag('all_selected_checkboxes_count', selected_vrns_count)
            = render 'vehicles_management/remove_vehicles/table'

            - if @pagination.total_vehicles_count > 10
              = render 'pagination'

              .govuk-form-group
                %fieldset.govuk-fieldset{'aria-describedby': 'per-page-dropdown'}
                  %legend.govuk-visually-hidden Results per page
                  = select_tag('per_page',
                               options_for_select(@pagination.results_per_page, params[:per_page]),
                               class: 'govuk-select moj-pagination__results results-per-page-select',
                               id: 'per-page-dropdown')
                  = label_tag('per-page-dropdown',
                              'Results per page',
                              class: 'govuk-label moj-pagination__results results-per-page-select')

            - if @pagination.total_vehicles_count.positive?
              %p
              .govuk-form-group
                = submit_tag('Continue',
                             class: 'govuk-button',
                             id: 'continue-remove-vehicles-button',
                             'data-module': 'govuk-button')

= javascript_pack_tag 'removeVehicles'

app/views/vehicles_management/remove_vehicles/vehicle_not_found.html.haml
- title_and_header = "You searched for #{@vrn}"
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper.govuk-main-wrapper--auto-spacing#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-full
      = render 'shared/error' if alert

      %h1.govuk-heading-l= title_and_header

      = form_for('payment', url: vehicle_not_found_fleets_path, method: :post) do |f|
        .govuk-form-group
          %label.govuk-label{for: 'vrn-search'}
            Search for a number plate
          - if alert
            = render 'vehicles_management/remove_vehicles/vrn_input/errored', message: alert
          - else
            = render 'vehicles_management/remove_vehicles/vrn_input/normal'

          = f.submit('Search',
                     class: 'govuk-button govuk-button--secondary',
                     id: 'search-form-submit',
                     'data-module': 'govuk-button')

          %p
            = link_to("Clear search (does not remove your selections)",
                      clear_search_fleets_path,
                      id: 'clear-search-link',
                      class: 'govuk-link')


      %h2.govuk-heading-l We could not find that vehicle
      %p
        It might be because:
        %ul.govuk-list-govuk-list--bullet
          %li
            %p You did not upload that vehicle to the list

app/views/vehicles_management/remove_vehicles/vehicles_to_remove_details.html.haml
- title_and_header = 'Vehicles to remove'
- content_for(:title, title_and_header)

= render 'shared/js_back_link'

%main.govuk-main-wrapper.govuk-main-wrapper--auto-spacing#main-content{role: 'main'}
  .govuk-grid-row
    .govuk-grid-column-two-thirds
      %h2.govuk-heading-l= title_and_header

      %table.govuk-table
        %thead.govuk-table__head
          %tr.govuk-table__row
            %th.govuk-table__header{scope: 'col', colspan: 2} Number plate
        %tbody.govuk-table__body
          - @vrns.each do |vrn|
            %tr.govuk-table__row
              %td.govuk-table__cell{scope: 'row'}=vrn

      %p= link_to('Return to confirmation', confirm_remove_vehicles_fleets_path, id: 'return-to-confirmation')